// <auto-generated />
using System;
using CyberBit.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CyberBit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210826083833_addnewuser3")]
    partial class addnewuser3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CyberBit.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DueDate");

                    b.Property<int>("Status");

                    b.Property<string>("Title");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new { Id = 1, DueDate = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Status = 1, Title = "working", UserId = 1 },
                        new { Id = 2, DueDate = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), Status = 1, Title = "eating", UserId = 1 },
                        new { Id = 3, DueDate = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Status = 2, Title = "working", UserId = 1 },
                        new { Id = 4, DueDate = new DateTime(2021, 8, 27, 11, 11, 0, 0, DateTimeKind.Unspecified), Status = 2, Title = "sleeping", UserId = 1 },
                        new { Id = 5, DueDate = new DateTime(2021, 8, 26, 11, 9, 0, 0, DateTimeKind.Unspecified), Status = 3, Title = "testing", UserId = 2 },
                        new { Id = 6, DueDate = new DateTime(2020, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), Status = 3, Title = "leaving", UserId = 2 }
                    );
                });

            modelBuilder.Entity("CyberBit.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, Name = "Oron" },
                        new { Id = 2, Name = "Tamir" },
                        new { Id = 3, Name = "Naama" },
                        new { Id = 4, Name = "Shmuel" },
                        new { Id = 5, Name = "Yusi" },
                        new { Id = 6, Name = "dotan" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
